name: build-action
on:
  push:
    branches:
      - main
jobs:
  build:
    name: website build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: checkout main branch
        uses: actions/checkout@main
      - name: install process
        run: yarn install
      - name: build process
        run: yarn build