name: build-action
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: website build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - name: checkout pages
        uses: actions/checkout@v2.3.1

      - name: install process
        run: yarn install

      - name: build process
        run: yarn build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: pages
          folder: docs